export const usersConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    FORGOT_REQUEST: 'USERS_FORGOT_REQUEST',
    FORGOT_SUCCESS: 'USERS_FORGOT_SUCCESS',
    FORGOT_FAILURE: 'USERS_FORGOT_FAILURE',

    RESET_REQUEST: 'USERS_RESET_REQUEST',
    RESET_SUCCESS: 'USERS_RESET_SUCCESS',
    RESET_FAILURE: 'USERS_RESET_FAILURE',

    EMPTY_BOOKMARKS_MOVIES: 'EMPTY_BOOKMARKS_MOVIES',
    EMPTY_BOOKMARKS_SERIES: 'EMPTY_BOOKMARKS_SERIES',

    EDIT_SUCCESS: 'USERS_EDIT_SUCCESS',
    EDIT_FAILURE: 'USERS_EDIT_FAILURE',

    GET_AVATAR: 'GET_AVATAR',

    GET_FAVORITES: 'GET_FAVORITES',
    GET_HISTORIE: 'GET_HISTORIE',

    GET_HISTORY: 'GET_HISTORY',
    ADD_HISTORY: 'ADD_HISTORY',
    DELETE_HISTORY: 'DELETE_HISTORY',

    LOGOUT: 'USERS_LOGOUT',
};
